# Generated by Django 5.1.6 on 2025-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='working_hours',
            field=models.CharField(default='5:30 a.m. - 2:30 p.m.', max_length=50),
        ),
    ]
