# Generated by Django 5.1.6 on 2025-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglot_latitude_parkinglot_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='location',
            new_name='location_name',
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck')], max_length=20),
        ),
    ]
