# Generated by Django 5.1.6 on 2025-03-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parkinglot_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='working_hours',
        ),
    ]
