# Generated by Django 5.1.6 on 2025-04-10 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_location_parkinglot_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
