# Generated by Django 5.1.5 on 2025-02-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-15 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='vehicle_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
