# Generated by Django 5.1.5 on 2025-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingLot',
        ),
        migrations.RenameField(
            model_name='parkingspace',
            old_name='image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='available',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='height',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='length',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='width',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='lot_name',
            field=models.CharField(default='Default Lot Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='vehicle_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
