# Generated by Django 5.1.4 on 2025-01-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkingspace_latitude_parkingspace_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_slot_owner',
            field=models.BooleanField(default=False),
        ),
    ]
