# Generated by Django 5.1.5 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkingspace_created_at_parkingspace_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
