# Generated by Django 5.1.4 on 2025-01-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_is_slot_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('slot_number', models.CharField(max_length=50)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parkingspace')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicletype')),
            ],
        ),
    ]
